{{- if .Values.serviceAccount.readonly -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.readonlyrolename }}
rules:
- apiGroups: ["*"]
  resources: ["clusterroles", "roles", "clusterrolebindings", "rolebindings", "cronjobs", "daemonsets", "deployments", "namespaces", "jobs", "nodes", "replicasets", "endpoints", "services", "serviceaccounts","statefulsets", "events"]
  verbs: ["get", "list", "watch"]
{{- end }}

