{{- if .Values.writeRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.writerolename }}
rules:

- apiGroups: ["*"]
  resources: ["clusterroles", "roles", "clusterrolebindings", "rolebindings", "cronjobs", "daemonsets", "deployments", "namespaces", "jobs", "nodes", "replicasets", "endpoints", "services", "serviceaccounts","statefulsets", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
{{-  if .Values.echoscan.enabled }}
  resources: ["*"]
  verbs: ["*"]
{{- else }}
  resources: ["pods"]
  verbs: ["delete", "watch", "get", "list"]
{{- end }}

{{- end }}
