{{- if .Values.writeRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.writerolename }}
rules:

- apiGroups: ["*"]
  resources: ["clusterroles", "roles", "clusterrolebindings", "rolebindings", "cronjobs", "daemonsets", "deployments", "namespaces", "jobs", "nodes", "replicasets", "endpoints", "services", "serviceaccounts","statefulsets", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["delete", "watch", "get", "list"]
{{- end }}
{{- if .Values.echoscan.enabled }}
#- apiGroups: ["*"]
#  resources: ["pods/ephemeralcontainers"]
#  verbs: ["update"]
#- apiGroups: ["*"]
#  resources: ["pods/log"]
#  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}

